import Head from 'next/head';
import React from 'react';
import Footer from '../components/Footer';

export default function Layout({ children }: React.PropsWithChildren) {
  return (
    <>
      <Head>
        <title>Video Commenting App Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-full container mx-auto pt-12">{children}</main>
      <Footer />
    </>
  );
}
